from fpdf import FPDF
import textwrap

class ProposalPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()
        self.set_font("Arial", size=12)
        
    def create_proposal(self, content):
        # Add company header
        self.set_font("Arial", "B", size=16)
        self.cell(0, 10, "Event Proposal", ln=True, align="C")
        self.ln(10)
        
        # Add content
        self.set_font("Arial", size=12)
        for line in content.split('\n'):
            # Wrap text to fit page width
            wrapped_lines = textwrap.wrap(line, width=75)
            for wrapped_line in wrapped_lines:
                self.cell(0, 10, wrapped_line, ln=True)
                
        # Add footer
        self.set_y(-30)
        self.set_font("Arial", "I", size=8)
        self.cell(0, 10, "Generated by Event Proposal Generator", ln=True, align="C")
        
    def save_pdf(self, filename):
        self.output(filename)

def generate_pdf(content, filename):
    pdf = ProposalPDF()
    pdf.create_proposal(content)
    pdf.save_pdf(filename)
    return filename
